import { MobilettoOrmTypeDef, MobilettoOrmFieldDefConfigs } from "mobiletto-orm";
export declare const USERNAME_MIN_LENGTH = 2;
export declare const USERNAME_MAX_LENGTH = 100;
export declare const EMAIL_MIN_LENGTH = 6;
export declare const EMAIL_MAX_LENGTH = 200;
export declare const PASSWORD_MIN_LENGTH = 8;
export declare const PASSWORD_MAX_LENGTH = 100;
export declare const primaryAccountFields: MobilettoOrmFieldDefConfigs;
export declare const ACCOUNT_TABLE_FIELDS: string[];
export declare const ACCOUNT_TEXT_SEARCH_FIELDS: string[];
export declare const AccountTypeDef: MobilettoOrmTypeDef;
export declare const AuthAccountTypeDef: MobilettoOrmTypeDef;
