// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
import { MobilettoOrmObject } from "mobiletto-orm-typedef";
export type Library_autoscanType = {
    initialDelay?: number;
    interval?: number;
};
export type LibraryType = MobilettoOrmObject & {
    name: string;
    media?: string;
    sources?: string[];
    destinations?: string[];
    autoscanEnabled: boolean;
    autoscan?: Library_autoscanType;
};
