// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
import { MobilettoOrmObject } from "mobiletto-orm-typedef";
export type MediaType = MobilettoOrmObject & {
    name: string;
    from?: string;
    ext: string[];
    packages?: string[];
};
