// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
import * as yup from "yup";
export const PublicConfigSchema = yup.object({
    public: yup.boolean()
        .typeError('public_invalid')
        .required('public_required'),
    title: yup.string()
        .typeError('title_invalid')
        .required('title_required')
        .default("Yuebing 🥮"),
    siteUrl: yup.string()
        .typeError('siteUrl_invalid')
        .required('siteUrl_required')
        .default("http://127.0.0.1:3000"),
    registrationEnabled: yup.boolean()
        .typeError('registrationEnabled_invalid')
        .required('registrationEnabled_required')
        .default(true),
    inviteFriendsEnabled: yup.boolean()
        .typeError('inviteFriendsEnabled_invalid')
        .required('inviteFriendsEnabled_required')
        .default(true),
    limitRegistration: yup.string()
        .matches(/^\s*([A-Z\d][A-Z\d._%+-]*@[A-Z\d.-]+\.[A-Z]{2,24}\s*,?\s*)+$/im, 'limitRegistration_regex')
        .typeError('limitRegistration_invalid')
        .notRequired(),
    defaultLocale: yup.string()
        .oneOf(["ar","bn","de","en","es","fr","ha","hi","id","it","ja","ko","mr","pl","pt","ru","sw","tl","tr","ur","vi","zh"], 'defaultLocale_enum')
        .typeError('defaultLocale_invalid')
        .required('defaultLocale_required')
        .default("en"),
    emailEnabled: yup.boolean()
        .typeError('emailEnabled_invalid')
        .required('emailEnabled_required'),
    isDefault: yup.boolean()
        .typeError('isDefault_invalid')
        .notRequired(),
});
