// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
import { MobilettoOrmObject } from "mobiletto-orm-typedef";
export type PublicConfigType = MobilettoOrmObject & {
    public: boolean;
    title: string;
    siteUrl: string;
    registrationEnabled: boolean;
    inviteFriendsEnabled: boolean;
    limitRegistration?: string;
    defaultLocale: string;
    emailEnabled: boolean;
    isDefault?: boolean;
    needsAdmin?: boolean;
};
