// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
import * as yup from "yup";
export const AuthAccountSchema = yup.object({
    username: yup.string()
        .min(2, 'username_min')
        .max(100, 'username_max')
        .matches(/^[A-Z][A-Z\d-._]+$/i, 'username_regex')
        .typeError('username_invalid')
        .required('username_required'),
    email: yup.string()
        .min(6, 'email_min')
        .max(200, 'email_max')
        .matches(/^[A-Z\d][A-Z\d._%+-]*@[A-Z\d.-]+\.[A-Z]{2,24}$/i, 'email_regex')
        .typeError('email_invalid')
        .required('email_required'),
    password: yup.string()
        .min(8, 'password_min')
        .max(100, 'password_max')
        .typeError('password_invalid')
        .required('password_required'),
    firstName: yup.string()
        .min(2, 'firstName_min')
        .max(100, 'firstName_max')
        .typeError('firstName_invalid')
        .notRequired(),
    lastName: yup.string()
        .min(2, 'lastName_min')
        .max(100, 'lastName_max')
        .typeError('lastName_invalid')
        .notRequired(),
    locale: yup.string()
        .oneOf(["ar", "bn", "de", "en", "es", "fr", "ha", "hi", "id", "it", "ja", "ko", "mr", "pl", "pt", "ru", "sw", "tl", "tr", "ur", "vi", "zh"], 'locale_enum')
        .typeError('locale_invalid')
        .required('locale_required'),
    flags: yup.array().of(yup.string()
        .oneOf(["flag_welcome_email", "flag_can_comment", "flag_can_tag", "flag_can_edit_metadata", "flag_can_set_thumbnail"], 'flags_enum')
        .typeError('flags_invalid'))
        .typeError('flags_invalid')
        .notRequired()
        .default(["flag_welcome_email", "flag_can_comment", "flag_can_tag"]),
    admin: yup.boolean()
        .typeError('admin_invalid')
        .notRequired(),
    verified: yup.number()
        .typeError('verified_invalid')
        .notRequired(),
    session: yup.string()
        .typeError('session_invalid')
        .notRequired(),
});
