export declare const LOCALE_ITEMS: {
    value: string;
    label: string;
    title: string;
}[];
export declare const EMAIL_REGEX: RegExp;
export declare const LIST_OF_EMAILS_REGEX: RegExp;
export declare const PATH_REGEX: RegExp;
export declare const REGEX_VALIDATORS: {
    locale: RegExp;
    username: RegExp;
    scan_id: RegExp;
    email: RegExp;
    host: RegExp;
    url: RegExp;
    content_type: RegExp;
    raw_hex: RegExp;
    hex: RegExp;
    volume: RegExp;
    local_path: RegExp;
    file_mode: RegExp;
    aws_key: RegExp;
    aws_secret: RegExp;
    s3_bucket: RegExp;
    b2_bucket: RegExp;
    path: RegExp;
};
export declare const isExactRegexMatch: (value: string, regex: RegExp) => boolean;
export declare const isValidEmail: (value: string) => boolean;
export declare const NORMALIZE_LOWERCASE: (v: unknown) => Promise<string>;
export declare const findValidEmails: (muck: string | string[], splitOn?: RegExp) => string[];
