// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
export type UsernameAndPasswordType = {
    _meta?: {
        id: string;
        version: string;
        removed?: boolean;
        ctime: number;
        mtime: number;
    };
    usernameOrEmail: string;
    password: string;
};
