// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
import { MobilettoOrmObject } from "mobiletto-orm-typedef";
export type UsernameAndPasswordType = MobilettoOrmObject & {
    usernameOrEmail: string;
    password: string;
};
