// DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen
import * as yup from "yup";
export const UsernameAndPasswordSchemaFields = {
    usernameOrEmail: yup.string().trim().transform(v => v === '' ? undefined : v)
        .min(2, 'usernameOrEmail_min')
        .max(200, 'usernameOrEmail_max')
        .typeError('usernameOrEmail_invalid')
        .required('usernameOrEmail_required'),
    password: yup.string().trim().transform(v => v === '' ? undefined : v)
        .min(8, 'password_min')
        .max(100, 'password_max')
        .typeError('password_invalid')
        .required('password_required'),
};
export const UsernameAndPasswordSchema = yup.object(UsernameAndPasswordSchemaFields);
